const surprisePrompts = [
  "A giraffe with a human necktie",
  "A dragon playing soccer with a beach ball",
  "A city skyline made of ice cream cones",
  "A treehouse on the moon with a slide that leads to Earth",
  "A giant snail riding a bicycle",
  "A mermaid lounging in a hot tub filled with pearls",
  "A castle made of clouds",
  "A flamingo wearing roller skates and a tutu",
  "A robot playing a grand piano",
  "A unicorn made of fire",
  "A garden of floating flowers",
  "A person walking on water in a pond filled with fish",
  "A whale swimming in a pool",
  "A tree growing from a teacup",
  "A frog prince kissing a human princess",
  "A polar bear playing a game of chess",
  "A house made of books",
  "A giant snake sleeping in a hammock",
  "A magical garden with flying fruit",
  "A giant spider web with a rainbow trapped inside",
  "A robot gardening in a floating garden",
  "A colorful elephant riding a unicycle",
  "A mermaid riding a seahorse",
  "A mountain made of candy",
  "A fairy garden with glowing mushrooms",
  "A tree with a swing made of vines",
  "A turtle flying a hot air balloon",
  "A wizard's library with floating books",
  "A waterfall made of chocolate",
  "A panda playing a guitar",
  "A flying car made of feathers",
  "A tree growing from a broken vase",
  "A snowman made of rainbow ice cream",
  "A castle made of crystal",
  "A peacock wearing a crown",
  "A giant frog playing a guitar",
  "A bridge made of clouds",
  "A robot made of flowers",
  "A fish swimming in a fishbowl",
  "A caterpillar riding a bicycle",
  "A tree with a slide made of leaves",
  "A treehouse with a view of the Milky Way",
  "A garden with a rainbow-colored fountain",
  "A robot with a garden growing from its head",
  "A waterfall made of rainbow water",
  "A giant octopus playing the drums",
  "A tree growing from a teapot",
  "A garden with a rainbow-colored flower arch",
  "A flamingo wearing a top hat and a monocle",
  "A castle made of sand",
  "A unicorn made of flowers",
]

export default surprisePrompts
